// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
// internal/web/templates/components.templ

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"encoding/json"
	"fmt"
	"html/template"
	"net/url"
	"strings"
	"time"

	"github.com/churndesk/churndesk/internal/domain"
	"github.com/churndesk/churndesk/internal/markdown"
)

// TypePill renders the item type badge.
func TypePill(t domain.ItemType) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{"pill", typePillClass(t)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(typeLabel(t))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 18, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// SourcePill renders the source (github repo or jira space).
func SourcePill(source, prOwner, prRepo string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if source == "github" && prRepo != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<span class=\"pill pill-muted\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(prOwner)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 24, Col: 41}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "/")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(prRepo)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 24, Col: 52}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if source == "jira" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<span class=\"pill pill-muted\">Jira</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// CommentPartial renders a single comment for HTMX append response.
func CommentPartial(author, body string, renderedBody template.HTML, createdAt time.Time) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"comment\" style=\"padding:12px 0;border-top:1px solid var(--border)\"><div class=\"flex gap-2 items-center\" style=\"margin-bottom:6px\"><span style=\"font-weight:600;font-size:13px\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(author)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 34, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</span> <span style=\"color:var(--muted);font-size:12px\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(createdAt.Format("Jan 2, 2006 15:04"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 35, Col: 90}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</span></div><div class=\"prose\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(string(renderedBody)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ErrorPartial renders an inline error for failed HTMX operations.
func ErrorPartial(message string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var11 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var11 == nil {
			templ_7745c5c3_Var11 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"pill pill-red\" style=\"display:block;padding:8px 12px;border-radius:6px\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var12 string
		templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(message)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 44, Col: 11}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ── Template helpers (plain Go functions, not templ components) ─────────────

func itemTypeClass(t domain.ItemType) string {
	switch t {
	case domain.ItemTypePRReviewNeeded:
		return "pr-review-needed"
	case domain.ItemTypePRStaleReview:
		return "pr-stale-review"
	case domain.ItemTypePRChangesRequested:
		return "pr-changes"
	case domain.ItemTypePRNewComment:
		return "pr-comment"
	case domain.ItemTypePRCIFailing:
		return "pr-ci-failing"
	case domain.ItemTypePRApproved:
		return "pr-approved"
	case domain.ItemTypeJiraStatusChange:
		return "jira-status"
	case domain.ItemTypeJiraComment:
		return "jira-comment"
	case domain.ItemTypeJiraNewBug:
		return "jira-bug"
	default:
		return ""
	}
}

func typePillClass(t domain.ItemType) string {
	switch t {
	case domain.ItemTypePRReviewNeeded:
		return "pill-accent"
	case domain.ItemTypePRStaleReview, domain.ItemTypePRChangesRequested,
		domain.ItemTypeJiraStatusChange:
		return "pill-amber"
	case domain.ItemTypePRCIFailing, domain.ItemTypeJiraNewBug:
		return "pill-red"
	case domain.ItemTypePRApproved:
		return "pill-green"
	case domain.ItemTypePRNewComment, domain.ItemTypeJiraComment:
		return "pill-blue"
	default:
		return "pill-muted"
	}
}

func typeLabel(t domain.ItemType) string {
	switch t {
	case domain.ItemTypePRReviewNeeded:
		return "Review needed"
	case domain.ItemTypePRStaleReview:
		return "Stale review"
	case domain.ItemTypePRChangesRequested:
		return "Changes requested"
	case domain.ItemTypePRNewComment:
		return "PR comment"
	case domain.ItemTypePRCIFailing:
		return "CI failing"
	case domain.ItemTypePRApproved:
		return "Approved"
	case domain.ItemTypeJiraStatusChange:
		return "Status update"
	case domain.ItemTypeJiraComment:
		return "Jira comment"
	case domain.ItemTypeJiraNewBug:
		return "New bug"
	default:
		return string(t)
	}
}

func unseenClass(seen int) string {
	if seen == 0 {
		return "unseen"
	}
	return ""
}

func intStr(n int) string { return fmt.Sprintf("%d", n) }

func relativeTime(t time.Time) string {
	d := time.Since(t)
	switch {
	case d < time.Minute:
		return "just now"
	case d < time.Hour:
		return fmt.Sprintf("%dm ago", int(d.Minutes()))
	case d < 24*time.Hour:
		return fmt.Sprintf("%dh ago", int(d.Hours()))
	default:
		return fmt.Sprintf("%dd ago", int(d.Hours()/24))
	}
}

// navigateToItem is a templ script component that calls the global navigateTo
// function (defined in app.js) with the item's sanitized URL. Using a script
// block ensures templ applies its safe JSON encoding for the string argument.
func navigateToItem(url string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_navigateToItem_9540`,
		Function: `function __templ_navigateToItem_9540(url){navigateTo(url)
}`,
		Call:       templ.SafeScript(`__templ_navigateToItem_9540`, url),
		CallInline: templ.SafeScriptInline(`__templ_navigateToItem_9540`, url),
	}
}

// sanitizeURL validates the URL scheme and strips characters that could break HTML attributes.
// Allowed characters follow RFC 3986 unreserved + reserved sets, minus single-quote and backslash.
// Non-whitelisted schemes (e.g. javascript:) are rejected entirely.
func sanitizeURL(rawURL string) string {
	if rawURL == "" {
		return ""
	}
	// Reject non-whitelisted schemes
	parsed, err := url.Parse(rawURL)
	if err != nil {
		return ""
	}
	// Reject protocol-relative URLs like "//evil.example"
	if strings.HasPrefix(rawURL, "//") {
		return ""
	}
	scheme := strings.ToLower(parsed.Scheme)
	switch scheme {
	case "", "http", "https", "mailto", "tel":
		// allowed
	default:
		return ""
	}
	var buf strings.Builder
	for _, c := range rawURL {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') ||
			c == '-' || c == '_' || c == '.' || c == '~' || c == ':' || c == '/' ||
			c == '?' || c == '#' || c == '[' || c == ']' || c == '@' ||
			c == '!' || c == '$' || c == '&' || c == '(' || c == ')' ||
			c == '*' || c == '+' || c == ',' || c == ';' || c == '=' || c == '%' {
			buf.WriteRune(c)
		}
	}
	return buf.String()
}

// itemDetailURL returns the internal detail-view URL for the given item.
// GitHub items route to /prs/:owner/:repo/:number, Jira items to /jira/:key.
// Unknown sources fall back to the sanitized external URL.
func itemDetailURL(item domain.Item) string {
	switch item.Source {
	case "github":
		if item.PROwner != "" && item.PRRepo != "" && item.ExternalID != "" {
			return fmt.Sprintf("/prs/%s/%s/%s", url.PathEscape(item.PROwner), url.PathEscape(item.PRRepo), url.PathEscape(item.ExternalID))
		}
	case "jira":
		if item.ExternalID != "" {
			return fmt.Sprintf("/jira/%s", url.PathEscape(item.ExternalID))
		}
	}
	return sanitizeURL(item.URL)
}

// prGroup holds a primary status item and any comment items for the same PR.
type prGroup struct {
	primary  domain.Item
	comments []domain.Item
}

// prRawTitle extracts the bare PR title from item metadata (pr_title field),
// falling back to the item title when metadata is absent or unparseable.
func prRawTitle(item domain.Item) string {
	if item.Metadata != "" {
		var m struct {
			PRTitle string `json:"pr_title"`
		}
		if err := json.Unmarshal([]byte(item.Metadata), &m); err == nil && m.PRTitle != "" {
			return m.PRTitle
		}
	}
	return item.Title
}

// groupFeedItems groups items by PR (owner/repo/number), separating the primary
// status item from comment items. Items that don't belong to a PR are each their
// own group. The output order follows the first appearance of each group key in
// the input slice, which preserves the score-sorted order from the store.
func groupFeedItems(items []domain.Item) []prGroup {
	type entry struct {
		primary  *domain.Item
		comments []domain.Item
	}
	keys := []string{}
	groups := map[string]*entry{}

	prKey := func(item domain.Item) string {
		if item.Source == "github" && item.PROwner != "" && item.ExternalID != "" {
			return item.PROwner + "/" + item.PRRepo + "/" + item.ExternalID
		}
		return item.ID
	}

	for i := range items {
		item := items[i]
		key := prKey(item)
		if _, ok := groups[key]; !ok {
			groups[key] = &entry{}
			keys = append(keys, key)
		}
		if item.Type == domain.ItemTypePRNewComment {
			groups[key].comments = append(groups[key].comments, item)
		} else {
			groups[key].primary = &item
		}
	}

	result := make([]prGroup, 0, len(keys))
	for _, key := range keys {
		e := groups[key]
		if e.primary == nil {
			if len(e.comments) == 0 {
				continue
			}
			result = append(result, prGroup{primary: e.comments[0], comments: e.comments[1:]})
		} else {
			result = append(result, prGroup{primary: *e.primary, comments: e.comments})
		}
	}
	return result
}

// firstLineText extracts a single plain-text preview line from a comment's
// metadata JSON. It skips HTML comments, blank lines, and GitHub alert markers
// (e.g. [!IMPORTANT]), strips blockquote prefixes and heading markers, and
// truncates to 80 runes.
func firstLineText(metadata string) string {
	if metadata == "" {
		return ""
	}
	var m struct {
		LatestComment string `json:"latest_comment"`
	}
	if err := json.Unmarshal([]byte(metadata), &m); err != nil || m.LatestComment == "" {
		return ""
	}
	for _, line := range strings.Split(m.LatestComment, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "<!--") {
			continue
		}
		// Strip blockquote prefixes ("> > text" → "text")
		for strings.HasPrefix(line, ">") {
			line = strings.TrimSpace(line[1:])
		}
		if line == "" {
			continue
		}
		// Skip GitHub alert type markers like [!IMPORTANT]
		if strings.HasPrefix(line, "[!") {
			continue
		}
		// Strip leading heading markers
		line = strings.TrimLeft(line, "#")
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		runes := []rune(line)
		if len(runes) > 80 {
			return string(runes[:80]) + "…"
		}
		return line
	}
	return ""
}

func extractLatestComment(metadata string) string {
	if metadata == "" {
		return ""
	}
	var m struct {
		LatestComment string `json:"latest_comment"`
	}
	if err := json.Unmarshal([]byte(metadata), &m); err != nil {
		return ""
	}
	runes := []rune(m.LatestComment)
	if len(runes) > 120 {
		return string(runes[:120]) + "…"
	}
	return m.LatestComment
}

// renderLatestComment extracts the latest_comment field from metadata JSON and
// returns it rendered as sanitized HTML via the shared markdown renderer.
func renderLatestComment(metadata string) template.HTML {
	if metadata == "" {
		return ""
	}
	var m struct {
		LatestComment string `json:"latest_comment"`
	}
	if err := json.Unmarshal([]byte(metadata), &m); err != nil || m.LatestComment == "" {
		return ""
	}
	return template.HTML(markdown.Render(m.LatestComment)) //nolint:gosec
}

var _ = templruntime.GeneratedTemplate
